**Import libraries**

In [1]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.87-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 590 kB/s
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24.0->yfinance) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.87

In [2]:
# load data:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
import yfinance as yf
drive.mount('/content/drive')

Mounted at /content/drive

**Data set #1 - List of SP500 companies**

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
stock = pd.read_html(url, header=0)[0]
stocks_df = stock['Symbol'].tolist()
stock

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,AOS,A. O. Smith,reports,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
3,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [99]:
print(stock["Symbol"].unique())

['MMM' 'AOS' 'ABT' 'ABBV' 'ABMD' 'ACN' 'ATVI' 'ADM' 'ADBE' 'ADP' 'AAP'
 'AES' 'AFL' 'A' 'APD' 'AKAM' 'ALK' 'ALB' 'ARE' 'ALGN' 'ALLE' 'LNT' 'ALL'
 'GOOGL' 'GOOG' 'MO' 'AMZN' 'AMCR' 'AMD' 'AEE' 'AAL' 'AEP' 'AXP' 'AIG'
 'AMT' 'AWK' 'AMP' 'ABC' 'AME' 'AMGN' 'APH' 'ADI' 'ANSS' 'AON' 'APA'
 'AAPL' 'AMAT' 'APTV' 'ACGL' 'ANET' 'AJG' 'AIZ' 'T' 'ATO' 'ADSK' 'AZO'
 'AVB' 'AVY' 'BKR' 'BALL' 'BAC' 'BBWI' 'BAX' 'BDX' 'WRB' 'BRK.B' 'BBY'
 'BIO' 'TECH' 'BIIB' 'BLK' 'BK' 'BA' 'BKNG' 'BWA' 'BXP' 'BSX' 'BMY' 'AVGO'
 'BR' 'BRO' 'BF.B' 'CHRW' 'CDNS' 'CZR' 'CPT' 'CPB' 'COF' 'CAH' 'KMX' 'CCL'
 'CARR' 'CTLT' 'CAT' 'CBOE' 'CBRE' 'CDW' 'CE' 'CNC' 'CNP' 'CDAY' 'CF'
 'CRL' 'SCHW' 'CHTR' 'CVX' 'CMG' 'CB' 'CHD' 'CI' 'CINF' 'CTAS' 'CSCO' 'C'
 'CFG' 'CLX' 'CME' 'CMS' 'KO' 'CTSH' 'CL' 'CMCSA' 'CMA' 'CAG' 'COP' 'ED'
 'STZ' 'CEG' 'COO' 'CPRT' 'GLW' 'CTVA' 'CSGP' 'COST' 'CTRA' 'CCI' 'CSX'
 'CMI' 'CVS' 'DHI' 'DHR' 'DRI' 'DVA' 'DE' 'DAL' 'XRAY' 'DVN' 'DXCM' 'FANG'
 'DLR' 'DFS' 'DISH' 'DIS' 'DG' 'DLTR' 'D' 'DPZ' 'DOV' 'DOW' 'DTE' 'DUK'
 'DD' 'DXC' 'EMN' 'ETN' 'EBAY' 'ECL' 'EIX' 'EW' 'EA' 'ELV' 'LLY' 'EMR'
 'ENPH' 'ETR' 'EOG' 'EPAM' 'EQT' 'EFX' 'EQIX' 'EQR' 'ESS' 'EL' 'ETSY' 'RE'
 'EVRG' 'ES' 'EXC' 'EXPE' 'EXPD' 'EXR' 'XOM' 'FFIV' 'FDS' 'FAST' 'FRT'
 'FDX' 'FITB' 'FRC' 'FE' 'FIS' 'FISV' 'FLT' 'FMC' 'F' 'FTNT' 'FTV' 'FBHS'
 'FOXA' 'FOX' 'BEN' 'FCX' 'GRMN' 'IT' 'GEN' 'GNRC' 'GD' 'GE' 'GIS' 'GM'
 'GPC' 'GILD' 'GL' 'GPN' 'GS' 'HAL' 'HIG' 'HAS' 'HCA' 'PEAK' 'HSIC' 'HSY'
 'HES' 'HPE' 'HLT' 'HOLX' 'HD' 'HON' 'HRL' 'HST' 'HWM' 'HPQ' 'HUM' 'HBAN'
 'HII' 'IBM' 'IEX' 'IDXX' 'ITW' 'ILMN' 'INCY' 'IR' 'INTC' 'ICE' 'IP' 'IPG'
 'IFF' 'INTU' 'ISRG' 'IVZ' 'INVH' 'IQV' 'IRM' 'JBHT' 'JKHY' 'J' 'JNJ'
 'JCI' 'JPM' 'JNPR' 'K' 'KDP' 'KEY' 'KEYS' 'KMB' 'KIM' 'KMI' 'KLAC' 'KHC'
 'KR' 'LHX' 'LH' 'LRCX' 'LW' 'LVS' 'LDOS' 'LEN' 'LNC' 'LIN' 'LYV' 'LKQ'
 'LMT' 'L' 'LOW' 'LUMN' 'LYB' 'MTB' 'MRO' 'MPC' 'MKTX' 'MAR' 'MMC' 'MLM'
 'MAS' 'MA' 'MTCH' 'MKC' 'MCD' 'MCK' 'MDT' 'MRK' 'META' 'MET' 'MTD' 'MGM'
 'MCHP' 'MU' 'MSFT' 'MAA' 'MRNA' 'MHK' 'MOH' 'TAP' 'MDLZ' 'MPWR' 'MNST'
 'MCO' 'MS' 'MOS' 'MSI' 'MSCI' 'NDAQ' 'NTAP' 'NFLX' 'NWL' 'NEM' 'NWSA'
 'NWS' 'NEE' 'NKE' 'NI' 'NDSN' 'NSC' 'NTRS' 'NOC' 'NCLH' 'NRG' 'NUE'
 'NVDA' 'NVR' 'NXPI' 'ORLY' 'OXY' 'ODFL' 'OMC' 'ON' 'OKE' 'ORCL' 'OGN'
 'OTIS' 'PCAR' 'PKG' 'PARA' 'PH' 'PAYX' 'PAYC' 'PYPL' 'PNR' 'PEP' 'PKI'
 'PFE' 'PCG' 'PM' 'PSX' 'PNW' 'PXD' 'PNC' 'POOL' 'PPG' 'PPL' 'PFG' 'PG'
 'PGR' 'PLD' 'PRU' 'PEG' 'PTC' 'PSA' 'PHM' 'QRVO' 'PWR' 'QCOM' 'DGX' 'RL'
 'RJF' 'RTX' 'O' 'REG' 'REGN' 'RF' 'RSG' 'RMD' 'RHI' 'ROK' 'ROL' 'ROP'
 'ROST' 'RCL' 'SPGI' 'CRM' 'SBAC' 'SLB' 'STX' 'SEE' 'SRE' 'NOW' 'SHW'
 'SBNY' 'SPG' 'SWKS' 'SJM' 'SNA' 'SEDG' 'SO' 'LUV' 'SWK' 'SBUX' 'STT'
 'STE' 'SYK' 'SIVB' 'SYF' 'SNPS' 'SYY' 'TMUS' 'TROW' 'TTWO' 'TPR' 'TRGP'
 'TGT' 'TEL' 'TDY' 'TFX' 'TER' 'TSLA' 'TXN' 'TXT' 'TMO' 'TJX' 'TSCO' 'TT'
 'TDG' 'TRV' 'TRMB' 'TFC' 'TYL' 'TSN' 'USB' 'UDR' 'ULTA' 'UNP' 'UAL' 'UPS'
 'URI' 'UNH' 'UHS' 'VLO' 'VTR' 'VRSN' 'VRSK' 'VZ' 'VRTX' 'VFC' 'VTRS'
 'VICI' 'V' 'VNO' 'VMC' 'WAB' 'WBA' 'WMT' 'WBD' 'WM' 'WAT' 'WEC' 'WFC'
 'WELL' 'WST' 'WDC' 'WRK' 'WY' 'WHR' 'WMB' 'WTW' 'GWW' 'WYNN' 'XEL' 'XYL'
 'YUM' 'ZBRA' 'ZBH' 'ZION' 'ZTS']

**Data set #2 - trim_jan_mar_2019**

In [107]:
#t = yf.download('MMM', start="2019-01-01", end="2019-01-01", group_by='ticker')
t = yf.download(stocks_df, start="2021-01-01", end="2021-12-31", group_by='ticker', interval= "3mo")
t

[*********************100%***********************]  503 of 503 completed

3 Failed downloads:
- CEG: Data doesn't exist for startDate = 1609477200, endDate = 1640926800
- BRK.B: No data found for this date range, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted

              PCG                                                    BALL  \
             Open   High    Low  Close Adj Close        Volume       Open
Date
2021-01-01  12.48  12.53  10.33  11.71     11.71  8.560025e+08  91.730003
2021-04-01  11.70  11.97   9.90  10.17     10.17  8.710120e+08  85.400002
2021-05-01    NaN    NaN    NaN    NaN       NaN           NaN        NaN
2021-07-01  10.18  10.53   8.24   9.60      9.60  1.113412e+09  81.320000
2021-08-01    NaN    NaN    NaN    NaN       NaN           NaN        NaN
2021-10-01   9.74  12.66   9.53  12.14     12.14  9.836994e+08  90.050003
2021-11-01    NaN    NaN    NaN    NaN       NaN           NaN        NaN

                                             ...         YUM              \
                 High        Low      Close  ...         Low       Close
Date                                         ...
2021-01-01  93.000000  80.739998  84.739998  ...  101.180000  108.180000
2021-04-01  94.290001  78.690002  81.019997  ...  107.989998  115.029999
2021-05-01        NaN        NaN        NaN  ...         NaN         NaN
2021-07-01  98.089996  77.949997  89.970001  ...  112.150002  122.309998
2021-08-01        NaN        NaN        NaN  ...         NaN         NaN
2021-10-01  97.610001  86.820000  96.269997  ...  121.209999  138.860001
2021-11-01        NaN        NaN        NaN  ...         NaN         NaN

                                           HIG                        \
             Adj Close       Volume       Open       High        Low
Date
2021-01-01  105.904884  108397000.0  49.630001  69.599998  47.470001
2021-04-01  113.150558   99181800.0  66.370003  69.940002  60.770000
2021-05-01         NaN          NaN        NaN        NaN        NaN
2021-07-01  120.812943   95459900.0  62.410000  72.199997  59.860001
2021-08-01         NaN          NaN        NaN        NaN        NaN
2021-10-01  137.672409   85680900.0  70.449997  78.169998  64.860001
2021-11-01         NaN          NaN        NaN        NaN        NaN


                Close  Adj Close       Volume
Date
2021-01-01  66.790001  64.918175  189942900.0
2021-04-01  61.970001  60.642284  161484100.0
2021-05-01        NaN        NaN          NaN
2021-07-01  70.250000  69.112732  118938200.0
2021-08-01        NaN        NaN          NaN
2021-10-01  69.040001  68.278954  103448400.0
2021-11-01        NaN        NaN          NaN

[7 rows x 3018 columns]

In [108]:
t = t.T
t.reset_index(inplace = True)
t

Date,level_0,level_1,2021-01-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00
0,PCG,Open,1.248000e+01,1.170000e+01,NaN,1.018000e+01,NaN,9.740000e+00,NaN
1,PCG,High,1.253000e+01,1.197000e+01,NaN,1.053000e+01,NaN,1.266000e+01,NaN
2,PCG,Low,1.033000e+01,9.900000e+00,NaN,8.240000e+00,NaN,9.530000e+00,NaN
3,PCG,Close,1.171000e+01,1.017000e+01,NaN,9.600000e+00,NaN,1.214000e+01,NaN
4,PCG,Adj Close,1.171000e+01,1.017000e+01,NaN,9.600000e+00,NaN,1.214000e+01,NaN
...,...,...,...,...,...,...,...,...,...
3013,HIG,High,6.960000e+01,6.994000e+01,NaN,7.220000e+01,NaN,7.817000e+01,NaN
3014,HIG,Low,4.747000e+01,6.077000e+01,NaN,5.986000e+01,NaN,6.486000e+01,NaN
3015,HIG,Close,6.679000e+01,6.197000e+01,NaN,7.025000e+01,NaN,6.904000e+01,NaN
3016,HIG,Adj Close,6.491817e+01,6.064228e+01,NaN,6.911273e+01,NaN,6.827895e+01,NaN
3017,HIG,Volume,1.899429e+08,1.614841e+08,NaN,1.189382e+08,NaN,1.034484e+08,NaN

In [109]:
#new_header = t.iloc[0]
#t.columns = new_header

t = t[t['level_1'] == 'Close']
t

Date,level_0,level_1,2021-01-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00
3,PCG,Close,11.710000,10.170000,NaN,9.600000,NaN,12.140000,NaN
9,BALL,Close,84.739998,81.019997,NaN,89.970001,NaN,96.269997,NaN
15,FLT,Close,268.630005,256.059998,NaN,261.269989,NaN,223.839996,NaN
21,PSA,Close,246.759995,300.690002,NaN,297.100006,NaN,374.559998,NaN
27,MRNA,Close,130.949997,234.979996,NaN,384.859985,NaN,253.979996,NaN
...,...,...,...,...,...,...,...,...,...
2991,CRM,Close,211.869995,244.270004,NaN,271.220001,NaN,254.130005,NaN
2997,FDX,Close,284.040009,298.329987,NaN,219.289993,NaN,258.640015,NaN
3003,SNPS,Close,247.779999,275.790009,NaN,299.410004,NaN,368.500000,NaN
3009,YUM,Close,108.180000,115.029999,NaN,122.309998,NaN,138.860001,NaN
3015,HIG,Close,66.790001,61.970001,NaN,70.250000,NaN,69.040001,NaN

In [110]:
t.to_excel('/content/drive/MyDrive/DAB103-DEMO/Q1-Q4_2021.xlsx', sheet_name = 'Sheet', index=False)

In [18]:
ene_dic_2019 = []

for ticker in stocks_df:
  print(ticker)
  y_2019 = yf.download('MMM', start="2019-01-01", end="2019-12-31", group_by='ticker',  interval= "3mo")['Close']
  ene_dic_2019.append(y_2019)

MMM
[*********************100%***********************]  1 of 1 completed
AOS
[*********************100%***********************]  1 of 1 completed
ABT
[*********************100%***********************]  1 of 1 completed
ABBV
[*********************100%***********************]  1 of 1 completed
ABMD

KeyboardInterrupt: ignored

In [16]:
ene_dic_2019

[Date
 2019-01-01    207.779999
 2019-04-01    173.339996
 2019-07-01    164.399994
 2019-10-01    176.419998
 Name: Close, dtype: float64, Date
 2019-01-01    53.320000
 2019-04-01    47.160000
 2019-07-01    47.709999
 2019-10-01    47.639999
 Name: Close, dtype: float64, Date
 2019-01-01    79.940002
 2019-04-01    84.099998
 2019-07-01    83.669998
 2019-10-01    86.860001
 Name: Close, dtype: float64, Date
 2019-01-01    80.589996
 2019-04-01    72.720001
 2019-07-01    75.720001
 2019-10-01    88.540001
 Name: Close, dtype: float64, Date
 2019-01-01    285.589996
 2019-04-01    260.489990
 2019-07-01    177.889999
 2019-10-01    170.589996
 Name: Close, dtype: float64, Date
 2019-01-01    176.020004
 2019-04-01    184.770004
 2019-07-01    192.350006
 2019-10-01    210.570007
 Name: Close, dtype: float64, Date
 2019-01-01    45.529999
 2019-04-01    47.200001
 2019-07-01    52.919998
 2019-10-01    59.419998
 Name: Close, dtype: float64, Date
 2019-01-01    43.130001
 2019-04-01    40.799999
 2019-07-01    41.070000
 2019-10-01    46.349998
 Name: Close, dtype: float64, Date
 2019-01-01    266.489990
 2019-04-01    294.649994
 2019-07-01    276.250000
 2019-10-01    329.809998
 Name: Close, dtype: float64, Date
 2019-01-01    159.740005
 2019-04-01    165.330002
 2019-07-01    161.419998
 2019-10-01    170.500000
 Name: Close, dtype: float64, Date
 2019-01-01    170.529999
 2019-04-01    154.139999
 2019-07-01    165.399994
 2019-10-01    160.160004
 Name: Close, dtype: float64, Date
 2019-01-01    18.08
 2019-04-01    16.76
 2019-07-01    16.34
 2019-10-01    19.90
 Name: Close, dtype: float64, Date
 2019-01-01    50.000000
 2019-04-01    54.810001
 2019-07-01    52.320000
 2019-10-01    52.900002
 Name: Close, dtype: float64, Date
 2019-01-01    80.379997
 2019-04-01    74.669998
 2019-07-01    76.629997
 2019-10-01    85.309998
 Name: Close, dtype: float64]

In [ ]:
oct_dic_2019_df = pd.DataFrame()
oct_dic_2019_df['index'] = stocks_df
oct_dic_2019_df['oct_dic_2019'] = oct_dic_2019
oct_dic_2019_df.to_excel('/content/drive/MyDrive/DAB103-DEMO/oct_dic_2019_df.xlsx', sheet_name='Sheet', index=False)

In [ ]:
oct_dic_2019_df.info()

In [ ]:
oct_dic_2019_df.describe()

In [ ]:
oct_dic_2019_df.isna().sum()

**Data set #3 - trim_jan_mar_2020**

IT companies are leading the SP500 index with 75 companies,  followed by Industrials(71) and Financial (66).

In [ ]:
jan_mar_2020 = []

for ticker in stocks_df:
  jan_mar_20 = yf.download(ticker, start="2020-01-01", end="2020-03-31", group_by='ticker')['Close'].mean()
  jan_mar_2020.append(jan_mar_20)

In [ ]:
jan_mar_2020_df = pd.DataFrame()
jan_mar_2020_df['index'] = stocks_df
jan_mar_2020_df['jan_mar_2020'] = jan_mar_2020
jan_mar_2020_df.to_excel('/content/drive/MyDrive/DAB103-DEMO/jan_mar_2020_df.xlsx', sheet_name='Sheet', index=False)

In [ ]:
jan_mar_2020_df.info()

In [ ]:
jan_mar_2020_df.describe()

In [ ]:
jan_mar_2020_df.isna().sum()

**Data set #4 - trim_jan_mar_2021**

In [ ]:
jan_mar_2021 = []

for ticker in stocks_df:
  jan_mar_21 = yf.download(ticker, start="2021-01-01", end="2021-03-31", group_by='ticker')['Close'].mean()
  jan_mar_2021.append(jan_mar_21)

In [ ]:
jan_mar_2021_df = pd.DataFrame()
jan_mar_2021_df['index'] = stocks_df
jan_mar_2021_df['jan_mar_2021'] = jan_mar_2021
jan_mar_2021_df.to_excel('/content/drive/MyDrive/DAB103-DEMO/jan_mar_2021_df.xlsx', sheet_name='Sheet', index=False)

In [ ]:
jan_mar_2021_df.info()

In [ ]:
jan_mar_2021_df.describe()

In [ ]:
jan_mar_2021_df.isna().sum()

**Data set #5 - Shares companies**

In [ ]:
sharesoutstanding = []

for ticker in stocks_df:
  print(ticker)
  tickerdata = yf.Ticker(ticker)
  try:
    sharesoutstanding.append(tickerdata.info['sharesOutstanding'])
  except:
    sharesoutstanding.append('')

sharesoutstanding_df = pd.DataFrame()
sharesoutstanding_df['sharesoutstanding'] = sharesoutstanding

In [ ]:
sharesoutstanding_df['index'] = stocks_df
sharesoutstanding_df['sharesOutstanding'] = sharesoutstanding
sharesoutstanding_df.to_excel('/content/drive/MyDrive/DAB103-DEMO/sharesoutstanding_df.xlsx', sheet_name='Sheet', index=False)