In [ ]:
# load data:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
stocks_df = pd.read_html(url, header=0)[0]
stocks_df.head()

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,AOS,A. O. Smith,reports,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
3,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981

In [ ]:
# Number of companies (there are mor because there are dual class stock structure and are listed more than once)
len(stocks_df)

503

In [ ]:
stocks_df['GICS Sector'].value_counts()

Information Technology    75
Industrials               71
Financials                66
Health Care               64
Consumer Discretionary    56
Consumer Staples          33
Real Estate               31
Utilities                 30
Materials                 28
Communication Services    26
Energy                    23
Name: GICS Sector, dtype: int64

In [ ]:
stocks_df['GICS Sub-Industry'].value_counts()

Health Care Equipment    19
Semiconductors           14
Industrial Machinery     14
Multi-Utilities          13
Application Software     13
                         ..
Diversified Chemicals     1
Leisure Products          1
Consumer Electronics      1
Copper                    1
Household Appliances      1
Name: GICS Sub-Industry, Length: 122, dtype: int64

In [ ]:
# load output with close values of each company:
#df_2019_1er = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/trim_jan_mar_2019.xlsx', index_col=0)
#df_2019_2er = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/trim_apr_jun_2019.xlsx', index_col=0)

df_2019_4to = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/trim_oct_dic_2019.xlsx', index_col=0)
#df_2020_1er = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/trim_jan_mar_2020.xlsx', index_col=0)
#df_2021 = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/trim_jan_mar_2021.xlsx', index_col=0)

df_shares = pd.read_excel('/content/drive/MyDrive/DAB103-DEMO/Project/Shares_Companies.xlsx', index_col=0)


#df_2019_1er.reset_index(inplace = True)
#df_2019_2er.reset_index(inplace = True)
#df_2020_1er.reset_index(inplace = True)
df_2019_4to.reset_index(inplace = True)
3#df_2021.reset_index(inplace = True)
df_shares.reset_index(inplace = True)

In [ ]:
#df_2019_4to

In [ ]:
#df_2020_1er = df_2020_1er[df_2020_1er['Attributes'] == 'Close']
#df_2020_1er = df_2020_1er[['Symbols','Jan_2020']]
#df_2020_1er['Jan_2020'] = round(df_2020_1er['Jan_2020'],2)
#df_2020_1er = df_2020_1er.rename(columns={"Jan_2020": "Jan_2020"})

df_2019_4to = df_2019_4to[df_2019_4to['Attributes'] == 'Close']
df_2019_4to = df_2019_4to[['Symbols','Dic_2019']]
df_2019_4to['Dic_2019'] = round(df_2019_4to['Dic_2019'],2)
df_2019_4to = df_2019_4to.rename(columns={"Dic_2019": "Dic_2019"})

df_2019_4to

    Symbols  Dic_2019
0       MMM    173.85
1       AOS     55.51
2       ABT    107.79
3      ABBV    105.08
4      ABMD    285.96
..      ...       ...
498    VRSK    199.10
499     WMT    146.58
500     WFC     29.38
501     WRK     43.99
502     WMB     21.28

[503 rows x 2 columns]

In [ ]:
#df_2021 = df_2021[df_2021['Attributes'] == 'Close']
#df_2021 = df_2021[['Symbols','Jan_2021']]
#df_2021['Jan_2021'] = round(df_2021['Jan_2021'],2)
#df_2021 = df_2021.rename(columns={"Jan_2021": "Jan_2021"})

#df_2021

In [ ]:
#df_shares['Shares'].fillna(0)
#df_shares['Shares'].astype(int)
df_shares = df_shares.rename(columns={"Symbol": "Symbols"})
#df_shares[df_shares['Symbol'] == 'OTIS']
#df_shares.tail()

In [ ]:
df_Avg_1 = df_2019_4to
#df_Avg_1['Jan_2020'] = df_2020_1er[['Jan_2020']]
#df_Avg_1['Jan_2021'] = df_2021[['Jan_2021']]

#df_Avg_1 = df_Avg_1.merge(df_shares, left_on='Symbols', right_on='Symbols', how='left')

#df_Avg.merge(df_shares, on='Symbols', how='left')
#df_Avg_1.head()

In [ ]:
# delete nan from dataset, it has to be an average of 3 filled columns:
#df_companies_na = df_Avg_1[df_Avg_1['Dic_2019'].isna() | df_Avg_1['Jan_2020'].isna() | df_Avg_1['Jan_2021'].isna()]
#print('Companies that were removed from dataset: ' + str(df_companies_na['Symbols'].unique()))

In [ ]:
df_Avg_1 = df_Avg_1.dropna()
df_Avg_1['Shares'] = df_Avg_1['Shares'].astype(int)
df_Avg_1.head()

KeyError: ignored

In [ ]:
# adding the market cap:
df_Avg_1["Marketcap_Dic_2019"] = df_Avg_1["Dic_2019"] * df_Avg_1["Shares"]
df_Avg_1["Marketcap_Dic_2019"] = df_Avg_1["Marketcap_Dic_2019"].astype(int)

df_Avg_1["Marketcap_Jan_2020"] = df_Avg_1["Jan_2020"] * df_Avg_1["Shares"]
df_Avg_1["Marketcap_Jan_2020"] = df_Avg_1["Marketcap_Jan_2020"].astype(int)

df_Avg_1["Marketcap_Jan_2021"] = df_Avg_1["Jan_2021"] * df_Avg_1["Shares"]
df_Avg_1["Marketcap_Jan_2021"] = df_Avg_1["Marketcap_Jan_2021"].astype(int)

df_Avg_1.head()

,Symbols,Dic_2019,Jan_2020,Jan_2021,Shares,Marketcap_Dic_2019,Marketcap_Jan_2020,Marketcap_Jan_2021
0,MMM,173.85,176.16,171.32,553614016,96245796681,97524645058,94845153221
1,AOS,55.51,46.40,56.43,128477000,7131758270,5961332800,7249957110
2,ABT,107.79,87.90,112.89,1751219968,188764000350,153932235187,197695222187
3,ABBV,105.08,86.97,108.45,1768099968,185791944637,153771654216,191750441529
4,ABMD,285.96,180.96,333.23,45460900,12999998964,8226604464,15148935707

In [ ]:
# change en el market cap:
df_Avg_1["%Marketcap_Jan_2020_Dic_2019"] = (df_Avg_1["Marketcap_Jan_2020"] - df_Avg_1["Marketcap_Dic_2019"]) / df_Avg_1["Marketcap_Dic_2019"]*100
df_Avg_1["%Marketcap_Jan_2021_Jan_2020"] = (df_Avg_1["Marketcap_Jan_2021"] - df_Avg_1["Marketcap_Jan_2020"]) / df_Avg_1["Marketcap_Jan_2020"]*100
df_Avg_1["%Marketcap_Jan_2021_Dic_2019"] = (df_Avg_1["Marketcap_Jan_2021"] - df_Avg_1["Marketcap_Dic_2019"]) / df_Avg_1["Marketcap_Dic_2019"]*100

In [ ]:
# % change stock prices:
df_Avg_1["PercentageChange_Jan_2020_Dic_2019"] = (df_Avg_1["Jan_2020"] - df_Avg_1["Dic_2019"]) / df_Avg_1["Dic_2019"]*100
df_Avg_1["PercentageChange_Jan_2021_Jan_2020"] = (df_Avg_1["Jan_2021"] - df_Avg_1["Jan_2020"]) / df_Avg_1["Jan_2020"]*100
df_Avg_1["PercentageChange_Jan_2021_Dic_2019"] = (df_Avg_1["Jan_2021"] - df_Avg_1["Dic_2019"]) / df_Avg_1["Dic_2019"]*100
df_Avg_1

KeyError: ignored

In [ ]:
# Change in total market cap:
sum(df_Avg_1['Marketcap_Jan_2020'] - df_Avg_1["Marketcap_Dic_2019"]) / 10**9

-2288.433436659

In [ ]:
sum(df_Avg_1["Marketcap_Jan_2021"] - df_Avg_1["Marketcap_Jan_2020"]) / 10**9

12644.30618339

In [ ]:
sum(df_Avg_1["Marketcap_Jan_2021"] - df_Avg_1["Marketcap_Dic_2019"]) / 10**9

10355.872746731

In [ ]:
stocks_df = stocks_df.merge(df_Avg_1, left_on='Symbol', right_on='Symbols', how='left', suffixes=('_x', ''))
stocks_df

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Symbols,...,Shares,Marketcap_Dic_2019,Marketcap_Jan_2020,Marketcap_Jan_2021,%Marketcap_Jan_2020_Dic_2019,%Marketcap_Jan_2021_Jan_2020,%Marketcap_Jan_2021_Dic_2019,PercentageChange_Jan_2020_Dic_2019,PercentageChange_Jan_2021_Jan_2020,PercentageChange_Jan_2021_Dic_2019
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902,MMM,...,5.536140e+08,9.624580e+10,9.752465e+10,9.484515e+10,1.328732,-2.747502,-1.455278,1.328732,-2.747502,-1.455278
1,AOS,A. O. Smith,reports,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,AOS,...,1.284770e+08,7.131758e+09,5.961333e+09,7.249957e+09,-16.411457,21.616379,1.657359,-16.411457,21.616379,1.657359
2,ABT,Abbott,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,ABT,...,1.751220e+09,1.887640e+11,1.539322e+11,1.976952e+11,-18.452547,28.430034,4.731422,-18.452547,28.430034,4.731422
3,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),ABBV,...,1.768100e+09,1.857919e+11,1.537717e+11,1.917504e+11,-17.234488,24.698172,3.207080,-17.234488,24.698172,3.207080
4,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,ABMD,...,4.546090e+07,1.300000e+10,8.226604e+09,1.514894e+10,-36.718422,84.145668,16.530284,-36.718422,84.145668,16.530284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,YUM,...,2.845420e+08,3.049437e+10,2.410071e+10,9.148026e+09,-20.966688,-62.042503,-70.000933,-20.966688,-62.042503,-70.000933
499,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,ZBRA,...,5.178990e+07,1.954706e+10,8.038310e+09,3.223403e+09,-58.877143,-59.899491,-83.509525,-58.877143,-59.899491,-83.509525
500,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,ZBH,...,2.098200e+08,3.022457e+10,1.419432e+10,6.267953e+10,-53.037140,341.581670,107.379382,-53.037140,341.581670,107.379382
501,ZION,Zions Bancorporation,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873,ZION,...,1.504710e+08,6.376961e+09,6.288183e+09,7.851577e+09,-1.392166,24.862407,23.124115,-1.392166,24.862407,23.124115
502,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,ZTS,...,4.681390e+08,7.524398e+10,1.409567e+10,2.098667e+10,-81.266721,48.887413,-72.108505,-81.266721,48.887413,-72.108505

In [ ]:
# Change in total market by sector:
(stocks_df.groupby("GICS Sector").sum()["Marketcap_Jan_2020"] - stocks_df.groupby("GICS Sector").sum()["Marketcap_Dic_2019"]).sort_values() / 10**9

GICS Sector
Information Technology   -2182.315390
Health Care               -783.355222
Consumer Discretionary    -195.313049
Materials                 -123.595655
Communication Services     -70.975059
Industrials                 29.915535
Consumer Staples            54.456164
Utilities                   95.749163
Real Estate                217.488474
Financials                 237.115418
Energy                     432.396183
dtype: float64

In [ ]:
(stocks_df.groupby("GICS Sector").sum()["Marketcap_Jan_2021"] - stocks_df.groupby("GICS Sector").sum()["Marketcap_Jan_2020"]).sort_values() / 10**9

GICS Sector
Materials                  -11.617710
Communication Services     500.341987
Real Estate                517.274157
Consumer Staples           630.039307
Utilities                  859.805553
Health Care                982.839985
Industrials               1047.599641
Consumer Discretionary    1121.663088
Financials                2229.242397
Information Technology    2383.323031
Energy                    2383.794747
dtype: float64

In [ ]:
# Companies by percentage change stock:
stocks_df.sort_values(by=["PercentageChange_Jan_2020_Dic_2019"])[["Security", "PercentageChange_Jan_2020_Dic_2019"]].head(5)

                     Security  PercentageChange_Jan_2020_Dic_2019
440     Teledyne Technologies                          -92.880452
446  Thermo Fisher Scientific                          -92.453477
450           TransDigm Group                          -91.812565
483        Waters Corporation                          -89.304703
459               Ulta Beauty                          -87.918507

In [ ]:
print(sum(stocks_df["PercentageChange_Jan_2020_Dic_2019"] < 0))
print(sum(stocks_df["PercentageChange_Jan_2020_Dic_2019"] > 0))

282
194

In [ ]:
# % change of stock by sector:
stocks_df.groupby("GICS Sector").mean()['PercentageChange_Jan_2020_Dic_2019'].sort_values()

GICS Sector
Information Technology   -15.653767
Materials                -13.480208
Health Care              -10.567470
Industrials               -0.963845
Communication Services     9.080312
Consumer Staples          12.147741
Financials                13.876037
Consumer Discretionary    14.537751
Utilities                 17.780136
Real Estate               47.806909
Energy                    67.151451
Name: PercentageChange_Jan_2020_Dic_2019, dtype: float64

In [ ]:
stocks_df.groupby("GICS Sub-Industry").mean()['PercentageChange_Jan_2020_Dic_2019'].sort_values()

GICS Sub-Industry
Trading Companies & Distributors       -76.317133
Food Distributors                      -53.165409
Copper                                 -49.695987
Environmental & Facilities Services    -42.302701
Specialty Stores                       -42.189187
                                          ...
Office REITs                           160.798840
Broadcasting                           223.119972
Apparel, Accessories & Luxury Goods    242.952223
Drug Retail                            463.018405
Multi-Sector Holdings                         NaN
Name: PercentageChange_Jan_2020_Dic_2019, Length: 122, dtype: float64

In [ ]:
print(sum(stocks_df.groupby("GICS Sub-Industry").mean()['PercentageChange_Jan_2020_Dic_2019'] < 0))
print(sum(stocks_df.groupby("GICS Sub-Industry").mean()['PercentageChange_Jan_2020_Dic_2019'] > 0))

74
47

In [ ]:
df_2019_4to

     Attributes Symbols    Oct_2019      Nov_2019      Dic_2019   Avg_Oct_Dic
0         Close     MMM  161.065217  1.708910e+02  1.738509e+02  1.686024e+02
1         Close     AOS   48.478696  5.018700e+01  5.550591e+01  5.139053e+01
2         Close     ABT   81.400000  8.401300e+01  1.077936e+02  9.106888e+01
3         Close    ABBV   75.651305  8.599800e+01  1.050773e+02  8.890886e+01
4         Close    ABMD  174.608696  2.053530e+02  2.859555e+02  2.219724e+02
...         ...     ...         ...           ...           ...           ...
1001     Volume    VRSK         NaN  1.022025e+06  6.159136e+05  8.189693e+05
1002     Volume     WMT         NaN  5.831030e+06  7.744023e+06  6.787526e+06
1003     Volume     WFC         NaN  1.644175e+07  3.353035e+07  2.498605e+07
1004     Volume     WRK         NaN  3.015975e+06  1.601195e+06  2.308585e+06
1005     Volume     WMB         NaN  1.107596e+07  9.888523e+06  1.048224e+07

[1006 rows x 6 columns]

In [ ]:
shape(df_2019_4to)

NameError: ignored